version: 0.0
os: linux
files:
  - source: /
    destination: drama
permissions:
  - object: drama/*
    mode: 4755
hooks:
  AfterInstall:
    - location: scripts/install_pip
  ApplicationStart:
    - location: scripts/start_drama